"""
Main training and inference pipeline.
This file is responsible for:
1. Loading the preprocessing results generated by preprocessing.py;
2. Building a 2D spatial 8-neighbor graph;
3. Performing the first-stage true/false zero discrimination task;
4. Performing the second-stage ESU + GAT imputation task;
5. Correcting the imputation results in the third stage;
6. Saving the models, evaluation results, and visualization results.
"""
import os
import json
import random
import secrets
from datetime import datetime
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
import umap
from pathlib import Path
from matplotlib.patches import Patch
from sklearn.cluster import SpectralClustering
from sklearn.metrics import (
    auc,
    classification_report,
    roc_auc_score,
    roc_curve,
)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from torch_geometric.data import Data
from torch_geometric.loader import NeighborLoader
from tqdm import tqdm
from model import Generator
from preprocessing import (
    BACKGROUND_FILENAME,
    MASK_FILENAME,
    MISSING_FILENAME,
    NORMALIZATION_FILENAME,
    Q_FILENAME,
)
def set_torch_random_seed(seed):
    seed = int(seed)

    random.seed(seed)
    torch.manual_seed(seed)

    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)


def save_run_metadata(metadata_path, metadata):
    with open(
        metadata_path,
        "w",
        encoding="utf-8"
    ) as metadata_file:
        json.dump(
            metadata,
            metadata_file,
            indent=4,
            ensure_ascii=False
        )
# ============================================================
# Standard 2D grid 8-neighbor graph
# ============================================================
def build_grid_8_neighbor_graph(height, width):
    """
    Build a standard 2D grid 8-neighbor graph.
    """
    print("Building the standard 2D grid 8-neighbor graph...")
    # Global node indices: (height, width)
    node_ids = torch.arange(
        height * width,
        dtype=torch.long
    ).reshape(height, width)
    # Number of undirected node pairs in the standard 8-neighbor graph:
    # horizontal + vertical + two diagonal directions
    num_undirected_pairs = (
        height * (width - 1)
        + (height - 1) * width
        + 2 * (height - 1) * (width - 1)
    )
    # Store both directions for each undirected node pair
    edge_index = torch.empty(
        (2, 2 * num_undirected_pairs),
        dtype=torch.long
    )
    cursor = 0
    def add_bidirectional_edges(source_nodes, target_nodes):
        nonlocal cursor
        source_nodes = source_nodes.reshape(-1)
        target_nodes = target_nodes.reshape(-1)
        num_edges = source_nodes.numel()
        # Forward edges: source -> target
        edge_index[0, cursor:cursor + num_edges] = source_nodes
        edge_index[1, cursor:cursor + num_edges] = target_nodes
        cursor += num_edges
        # Reverse edges: target -> source
        edge_index[0, cursor:cursor + num_edges] = target_nodes
        edge_index[1, cursor:cursor + num_edges] = source_nodes
        cursor += num_edges
    # 1. Horizontal adjacency: left <-> right
    add_bidirectional_edges(
        node_ids[:, :-1],
        node_ids[:, 1:]
    )
    # 2. Vertical adjacency: top <-> bottom
    add_bidirectional_edges(
        node_ids[:-1, :],
        node_ids[1:, :]
    )
    # 3. Main diagonal adjacency: upper-left <-> lower-right
    add_bidirectional_edges(
        node_ids[:-1, :-1],
        node_ids[1:, 1:]
    )
    # 4. Secondary diagonal adjacency: upper-right <-> lower-left
    add_bidirectional_edges(
        node_ids[:-1, 1:],
        node_ids[1:, :-1]
    )
    print(
        f"Standard 8-neighbor graph construction completed: "
        f"number of nodes={height * width}, "
        f"number of directed edges={edge_index.shape[1]}"
    )
    return edge_index
# ============================================================
# Map tissue-region cluster labels back to the 2D spatial grid
# ============================================================
def map_to_spatial_grid(
    cluster_labels,
    tissue_pixel_indices,
    height,
    width
):
    """
    Map cluster labels from the tissue region to a 2D spatial matrix.
    """
    spatial_cluster_map = np.full(
        (height, width),
        -1,
        dtype=int
    )
    for local_idx, global_idx in enumerate(tissue_pixel_indices):
        row_idx, col_idx = divmod(global_idx, width)
        spatial_cluster_map[row_idx, col_idx] = cluster_labels[local_idx]
    return spatial_cluster_map
# ============================================================
# Moran's I related functions
# ============================================================
def build_tissue_neighbor_edges(tissue_mask, connectivity=8):
    """
    Build 2D spatial adjacency edges only within the tissue region.
    """
    height, width = tissue_mask.shape
    id_map = -np.ones(
        (height, width),
        dtype=np.int64
    )
    id_map[tissue_mask] = np.arange(np.sum(tissue_mask))
    if connectivity == 4:
        offsets = [
            (1, 0),
            (0, 1)
        ]
    elif connectivity == 8:
        offsets = [
            (1, 0),
            (0, 1),
            (1, 1),
            (1, -1)
        ]
    else:
        raise ValueError("connectivity must be 4 or 8")
    src_list = []
    dst_list = []
    for dr, dc in offsets:
        r0 = max(0, -dr)
        r1 = min(height, height - dr)
        c0 = max(0, -dc)
        c1 = min(width, width - dc)
        source_block = id_map[r0:r1, c0:c1]
        target_block = id_map[
            r0 + dr:r1 + dr,
            c0 + dc:c1 + dc
        ]
        valid_mask = (
            (source_block >= 0)
            & (target_block >= 0)
        )
        source_nodes = source_block[valid_mask].ravel()
        target_nodes = target_block[valid_mask].ravel()
        src_list.append(source_nodes)
        dst_list.append(target_nodes)
        src_list.append(target_nodes)
        dst_list.append(source_nodes)
    if len(src_list) > 0:
        src = np.concatenate(src_list)
        dst = np.concatenate(dst_list)
    else:
        src = np.array([], dtype=np.int64)
        dst = np.array([], dtype=np.int64)
    return src, dst
def moran_i_binary(x, src, dst):
    """
    Compute Global Moran's I.
    """
    x = x.astype(np.float64)
    num_nodes = x.size
    if num_nodes == 0 or len(src) == 0:
        return np.nan
    x_mean = x.mean()
    centered_x = x - x_mean
    denominator = np.sum(centered_x ** 2)
    if denominator < 1e-12:
        return np.nan
    total_weight = len(src)
    numerator = np.sum(centered_x[src] * centered_x[dst])
    return (num_nodes / total_weight) * (numerator / denominator)
def compute_cluster_moran_metrics(
    spatial_cluster_map,
    tissue_mask,
    n_clusters,
    connectivity=8
):
    """
    Compute Moran's I for each cluster region.
    """
    src, dst = build_tissue_neighbor_edges(
        tissue_mask,
        connectivity
    )
    tissue_cluster_labels = spatial_cluster_map[tissue_mask]
    records = []
    for cluster_id in range(n_clusters):
        cluster_binary = (
            tissue_cluster_labels == cluster_id
        ).astype(np.float64)
        area = int(np.sum(cluster_binary))
        moran_value = (
            moran_i_binary(cluster_binary, src, dst)
            if area > 0
            else np.nan
        )
        records.append(
            {
                "cluster": cluster_id,
                "area": area,
                "moran_I": moran_value
            }
        )
    return pd.DataFrame(records)
# ============================================================
# Main pipeline
# ============================================================
def run_pipeline(
    data_dir,
    input_shape,
    output_dir,
    gpu_id=2,
    random_seed=42,
    torch_seed=None,
    output_filename="DropMSI.csv"
):
    """
    Run the complete two-stage training, imputation,
    and correction pipeline.
    """
    # ========================================================
    # 1. Paths and basic configuration
    # ========================================================
    data_dir = os.fspath(data_dir)
    output_dir = os.fspath(output_dir)
    if len(input_shape) != 2:
        raise ValueError("[height, width]")
    H, W = input_shape
    H = int(H)
    W = int(W)
    No = H * W
    os.makedirs(output_dir, exist_ok=True)
    np.random.seed(random_seed)

    maximum_seed = 2 ** 63 - 1

    if torch_seed is None:
        torch_seed = secrets.randbelow(
            maximum_seed
        )

    torch_seed = int(torch_seed)

    if torch_seed < 0 or torch_seed > maximum_seed:
        raise ValueError(
            f"torch_seed must be within [0, {maximum_seed}]."
        )

    stage1_torch_seed = torch_seed

    stage2_torch_seed = (
        torch_seed + 1
    ) % maximum_seed

    os.environ.setdefault(
        "CUBLAS_WORKSPACE_CONFIG",
        ":4096:8"
    )

    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True

    torch.use_deterministic_algorithms(
        True,
        warn_only=True
    )

    set_torch_random_seed(
        stage1_torch_seed
    )

    run_id = datetime.now().strftime(
        "%Y%m%d_%H%M%S_%f"
    )

    metadata_dir = os.path.join(
        Path(__file__).resolve().parent,
        "results",
        "run_metadata"
    )

    os.makedirs(
        metadata_dir,
        exist_ok=True
    )

    metadata_path = os.path.join(
        metadata_dir,
        f"run_{run_id}_seed_{torch_seed}.json"
    )

    # ========================================================
    # Device configuration
    # ========================================================
    use_gpu = torch.cuda.is_available()
    device = (
        torch.device(f"cuda:{gpu_id}")
        if use_gpu
        else torch.device("cpu")
    )
    print(f"Current device: {device}")

    if use_gpu:
        gpu_name = torch.cuda.get_device_name(
            device
        )
    else:
        gpu_name = None

    run_metadata = {
        "run_id": run_id,
        "status": "running",
        "numpy_seed": int(random_seed),
        "base_torch_seed": int(torch_seed),
        "stage1_torch_seed": int(
            stage1_torch_seed
        ),
        "stage2_torch_seed": int(
            stage2_torch_seed
        ),
        "input_shape": [
            int(H),
            int(W)
        ],
        "num_nodes": int(No),
        "data_dir": os.path.abspath(
            data_dir
        ),
        "output_dir": os.path.abspath(
            output_dir
        ),
        "output_filename": output_filename,
        "gpu_id": int(gpu_id),
        "gpu_name": gpu_name,
        "torch_version": str(
            torch.__version__
        ),
        "cuda_version": (
            str(torch.version.cuda)
            if torch.version.cuda is not None
            else None
        ),
        "cuda_available": bool(
            torch.cuda.is_available()
        ),
    }

    save_run_metadata(
        metadata_path,
        run_metadata
    )

    print("=" * 60)
    print("Random seed information")
    print("=" * 60)

    print(
        f"NumPy seed: {random_seed}"
    )

    print(
        f"Base PyTorch seed: {torch_seed}"
    )

    print(
        f"Stage 1 PyTorch seed: "
        f"{stage1_torch_seed}"
    )

    print(
        f"Stage 2 PyTorch seed: "
        f"{stage2_torch_seed}"
    )

    print(
        f"Run metadata file: "
        f"{metadata_path}"
    )

    print("=" * 60)
    # ========================================================
    # 2. Input file paths
    # ========================================================
    normalization_path = os.path.join(
        data_dir,
        NORMALIZATION_FILENAME
    )
    missing_path = os.path.join(
        data_dir,
        MISSING_FILENAME
    )
    mask_path = os.path.join(
        data_dir,
        MASK_FILENAME
    )
    q_path = os.path.join(
        data_dir,
        Q_FILENAME
    )
    background_path = os.path.join(
        data_dir,
        BACKGROUND_FILENAME
    )
    required_paths = [
        normalization_path,
        missing_path,
        mask_path,
        q_path,
        background_path,
    ]
    for required_path in required_paths:
        if not os.path.isfile(required_path):
            raise FileNotFoundError(
                f"Missing preprocessing file: {required_path}"
            )
    # ========================================================
    # 3. Output file paths
    # ========================================================
    cluster_vis_dir = output_dir
    best_discriminator_path = os.path.join(
        output_dir,
        "best_discriminator.pth"
    )
    best_full_model_path = os.path.join(
        output_dir,
        "best_imputation.pth"
    )
    final_output_path = os.path.join(
        output_dir,
        output_filename
    )
    temp_imputed_path = os.path.join(
        output_dir,
        "temp_imputed.npy"
    )
    temp_s_path = os.path.join(
        output_dir,
        "temp_s.npy"
    )
    # ========================================================
    # 4. Load NPY data
    # ========================================================
    print(f"Starting data loading: number of nodes={No}")
    Data_np = np.load(
        normalization_path,
        mmap_mode="r"
    )
    Missing_np = np.load(
        missing_path,
        mmap_mode="r"
    ).T
    s_np = np.load(
        mask_path,
        mmap_mode="r"
    ).T
    q_np = np.load(
        q_path,
        mmap_mode="r"
    ).T
    bg_data_np = np.load(
        background_path,
        mmap_mode="r"
    )
    Dim = Data_np.shape[1]
    print(
        f"Starting data loading: "
        f"number of nodes={No}, number of features={Dim}"
    )
    print("Preloading data...")
    X_np = np.array(Data_np)
    M_np = np.array(Missing_np)
    S_np = np.array(s_np)
    Q_np = np.array(q_np)
    BG_np = np.array(bg_data_np).reshape(-1, 1)
    print("Data loading completed")
    # ========================================================
    # 5. Build the standard 2D grid 8-neighbor graph
    # ========================================================
    edge_index = build_grid_8_neighbor_graph(H, W)
    E = edge_index.shape[1]
    print(f"Edge index construction completed: E={E}")
    # ========================================================
    # Encapsulate the PyG Data object
    # ========================================================
    graph_data = Data(
        x=torch.from_numpy(np.array(Data_np)),
        m=torch.from_numpy(np.array(Missing_np)),
        s_mask=torch.from_numpy(np.array(s_np)),
        q=torch.from_numpy(np.array(q_np)),
        bg=torch.from_numpy(np.array(bg_data_np)),
        edge_index=edge_index
    )
    # ========================================================
    # Stage 1: True/false zero discrimination task
    # ========================================================
    print("=" * 50)
    print("Stage 1: Starting true/false zero discrimination")
    print("=" * 50)
    N_CLUSTERS = 18
    # ========================================================
    # 1. Tissue region
    #
    # BG_np:
    #   0 = background
    #   1 = tissue
    # ========================================================
    tissue_mask_flat = BG_np[:, 0] == 1
    tissue_mask_2d = tissue_mask_flat.reshape(H, W)
    tissue_indices = np.where(tissue_mask_flat)[0]
    print(
        f"Number of tissue-region pixels: "
        f"{len(tissue_indices)} / {No}"
    )
    print(
        f"Number of background-region pixels: "
        f"{No - len(tissue_indices)} / {No}"
    )
    # ========================================================
    # 2. Extract the original data from the tissue region
    # ========================================================
    tissue_data = X_np[tissue_indices]
    # ========================================================
    # 3. Feature standardization
    # ========================================================
    print("Standardizing features...")
    standard_scaler = StandardScaler()
    scaled_data = standard_scaler.fit_transform(tissue_data)
    # ========================================================
    # 4. UMAP dimensionality reduction
    # ========================================================
    print("Performing UMAP dimensionality reduction...")
    reducer = umap.UMAP(
        n_neighbors=15,
        min_dist=0.1,
        n_components=3,
        metric="cosine",
        random_state=42
    )
    umap_embedding = reducer.fit_transform(scaled_data)
    # ========================================================
    # 5. Spectral clustering
    # ========================================================
    print("Performing spectral clustering...")
    clusters = SpectralClustering(
        n_clusters=N_CLUSTERS,
        affinity="nearest_neighbors",
        n_neighbors=15,
        eigen_solver="arpack",
        assign_labels="kmeans",
        n_jobs=-1,
        random_state=42
    ).fit_predict(umap_embedding)
    spatial_clusters_raw = map_to_spatial_grid(
        clusters,
        tissue_indices,
        H,
        W
    )
    # ========================================================
    # Moran's I filtering
    # ========================================================
    MORAN_CONNECTIVITY = 8
    MORAN_THRESHOLD = 0.25
    print(
        "Computing Moran's I for each cluster "
        "and filtering spatially dispersed clusters..."
    )
    moran_metrics_df = compute_cluster_moran_metrics(
        spatial_cluster_map=spatial_clusters_raw,
        tissue_mask=tissue_mask_2d,
        n_clusters=N_CLUSTERS,
        connectivity=MORAN_CONNECTIVITY
    )
    moran_metrics_df["valid_by_moran"] = (
        moran_metrics_df["moran_I"].notna()
        & (
            moran_metrics_df["moran_I"]
            >= MORAN_THRESHOLD
        )
    )
    valid_cluster_ids = (
        moran_metrics_df.loc[
            moran_metrics_df["valid_by_moran"],
            "cluster"
        ]
        .astype(int)
        .tolist()
    )
    removed_cluster_ids = (
        moran_metrics_df.loc[
            ~moran_metrics_df["valid_by_moran"],
            "cluster"
        ]
        .astype(int)
        .tolist()
    )
    print("Moran's I metrics for each cluster:")
    print(moran_metrics_df.to_string(index=False))
    spatial_clusters = spatial_clusters_raw.copy()
    for cluster_id in removed_cluster_ids:
        spatial_clusters[spatial_clusters == cluster_id] = -1
    npy_save_path = os.path.join(
        cluster_vis_dir,
        "spatial_clusters.npy"
    )
    np.save(npy_save_path, spatial_clusters)
    print(f"Cluster label matrix saved to: {npy_save_path}")
    print(
        f"Cluster ID range: "
        f"{np.min(spatial_clusters)} ~ "
        f"{np.max(spatial_clusters)}"
    )
    # ========================================================
    # 6. Visualize clustering results
    # ========================================================
    print("Generating clustering visualization...")
    colors = plt.cm.tab20(
        np.linspace(
            0,
            1,
            N_CLUSTERS
        )
    )
    rgb_image = np.zeros((H, W, 3))
    for cluster_id in valid_cluster_ids:
        current_cluster_mask = spatial_clusters == cluster_id
        if np.any(current_cluster_mask):
            rgb_image[current_cluster_mask] = colors[cluster_id][:3]
    plt.figure(figsize=(10, 6))
    plt.imshow(rgb_image)
    plt.title(
        f"Moran-filtered Spectral Clustering "
        f"(I >= {MORAN_THRESHOLD})",
        fontsize=14,
        fontweight="bold"
    )
    plt.axis("off")
    legend_elements = [
        Patch(
            facecolor=(0, 0, 0),
            label="Background / Removed"
        )
    ]
    for cluster_id in valid_cluster_ids:
        legend_elements.append(
            Patch(
                facecolor=colors[cluster_id][:3],
                label=f"Cluster {cluster_id}"
            )
        )
    plt.legend(
        handles=legend_elements,
        loc="upper right",
        bbox_to_anchor=(1.25, 1)
    )
    cluster_figure_path = os.path.join(
        cluster_vis_dir,
        "spatial_clustering.png"
    )
    plt.savefig(
        cluster_figure_path,
        dpi=300,
        bbox_inches="tight"
    )
    plt.close()
    print(f"Clustering visualization saved to: {cluster_figure_path}")
    # ========================================================
    # 7. Precompute the zero rate for each feature-cluster region
    # ========================================================
    print("Precomputing the missing rate for each feature-cluster region...")
    cluster_missing_rates = np.zeros(
        (Dim, N_CLUSTERS)
    )
    for feature_idx in tqdm(
        range(Dim),
        desc="Precomputing cluster missing rates"
    ):
        x_channel_2d = X_np[:, feature_idx].reshape(H, W)
        for cluster_id in range(N_CLUSTERS):
            cluster_mask_2d = spatial_clusters == cluster_id
            if not np.any(cluster_mask_2d):
                cluster_missing_rates[
                    feature_idx,
                    cluster_id
                ] = 1.0
                continue
            cluster_pixels = x_channel_2d[cluster_mask_2d]
            missing_count = np.sum(cluster_pixels < 1e-5)
            total_count = len(cluster_pixels)
            cluster_missing_rates[
                feature_idx,
                cluster_id
            ] = missing_count / total_count
    # ========================================================
    # 8. Filter all rule-based true zeros
    # ========================================================
    print("=" * 50)
    print("Starting the true/false zero discrimination process")
    print("=" * 50)
    missing_rate_threshold = 0.8
    rule_true_zero_mask = np.zeros(
        (No, Dim),
        dtype=bool
    )
    print("Filtering true zeros...")
    for feature_idx in tqdm(
        range(Dim),
        desc="Filtering true zeros"
    ):
        x_channel_2d = X_np[:, feature_idx].reshape(H, W)
        for cluster_id in valid_cluster_ids:
            cluster_mask_2d = spatial_clusters == cluster_id
            if not np.any(cluster_mask_2d):
                continue
            missing_rate = cluster_missing_rates[
                feature_idx,
                cluster_id
            ]
            if missing_rate >= missing_rate_threshold:
                true_zero_mask_2d = (
                    cluster_mask_2d
                    & (x_channel_2d < 1e-5)
                )
                rule_true_zero_mask[
                    :,
                    feature_idx
                ] |= true_zero_mask_2d.ravel()
    true_zero_candidate_count = int(np.sum(rule_true_zero_mask))
    print(
        f"Total number of true zeros obtained by rule-based filtering: "
        f"{true_zero_candidate_count}"
    )
    # ========================================================
    # 9. Initialize Stage 1 variables
    #
    # labels:
    #    0 = training true zero
    #    1 = training false zero
    #   -1 = excluded from BCE
    #
    # selected_fake_mask:
    #   Artificial false zeros independently selected from X > 0
    #   positions in Stage 1.
    # ========================================================
    labels = np.full(
        (No, Dim),
        -1,
        dtype=np.int8
    )
    selected_fake_mask = np.zeros(
        (No, Dim),
        dtype=bool
    )
    # ========================================================
    # Known false-zero positions
    # ========================================================
    known_fake_zero_q_mask = (
        (S_np == 0)
        & (Q_np == 0)
    )
    # Initialize the final forced false-zero mask:
    # It must include at least all known artificial masked positions S=0.
    force_fake_zero_q_mask = known_fake_zero_q_mask.copy()
    # The forced true-zero mask is generated later
    # in the non-skipping branch.
    force_true_zero_q_mask = np.zeros(
        (No, Dim),
        dtype=bool
    )
    print(
        f"Number of known artificial false-zero positions "
        f"(S=0 and Q=0): {np.sum(known_fake_zero_q_mask)}"
    )
    skip_discriminator = true_zero_candidate_count == 0
    if skip_discriminator:
        print(
            "No true zeros were selected; "
            "skipping Stage 1 discriminator training."
        )
        pred_labels = np.full(
            (No, Dim),
            -1,
            dtype=np.int8
        )
        print("=" * 50)
        print(
            "Stage 1 skipped: "
            "the Stage 2 imputation results will be retained directly"
        )
        print("=" * 50)
    else:
        # ====================================================
        # 10. Independently construct artificial false-zero
        #     candidates for Stage 1
        # ====================================================
        observed_candidate_mask = (
            tissue_mask_flat[:, None]
            & (X_np > 0)
        )
        true_pool_flat = np.flatnonzero(rule_true_zero_mask.ravel())
        observed_pool_flat = np.flatnonzero(observed_candidate_mask.ravel())
        observed_value_count = len(observed_pool_flat)
        print(
            f"Number of observed values with X > 0 in the tissue region: "
            f"{observed_value_count}"
        )
        if observed_value_count == 0:
            raise RuntimeError(
                "No observed values with X > 0 exist; "
                "unable to construct artificial true/false zero labels."
            )
        # ====================================================
        # 11. Two branches for determining the label counts
        # ====================================================
        if true_zero_candidate_count > observed_value_count:
            FAKE_MASK_RATE = 0.10
            num_fake_labels = int(
                observed_value_count * FAKE_MASK_RATE
            )
            if num_fake_labels == 0:
                raise RuntimeError(
                    "Too few observed values; "
                    "unable to generate false-zero labels at a 10% rate."
                )
            num_true_labels = num_fake_labels
            selected_true_flat = np.random.choice(
                true_pool_flat,
                size=num_true_labels,
                replace=False
            )
            selected_fake_flat = np.random.choice(
                observed_pool_flat,
                size=num_fake_labels,
                replace=False
            )
            print(
                f"Branch 1: number of true zeros "
                f"({true_zero_candidate_count}) > "
                f"number of observed values ({observed_value_count})"
            )
            print(
                f"Selecting 10% of the observed values as false zeros: "
                f"{num_fake_labels}"
            )
            print(
                f"Selecting the same number of true zeros from the rule-based "
                f"true-zero candidates: {num_true_labels}"
            )
        else:
            num_true_labels = true_zero_candidate_count
            num_fake_labels = true_zero_candidate_count
            # Use all rule-based true zeros
            selected_true_flat = true_pool_flat
            # Randomly select the same number of false zeros from observed values
            selected_fake_flat = np.random.choice(
                observed_pool_flat,
                size=num_fake_labels,
                replace=False
            )
            print(
                f"Branch 2: number of true zeros "
                f"({true_zero_candidate_count}) <= "
                f"number of observed values ({observed_value_count})"
            )
            print(
                f"Using all rule-based true zeros: "
                f"{num_true_labels}"
            )
            print(
                f"Selecting the same number of observed values as false zeros: "
                f"{num_fake_labels}"
            )
        # ====================================================
        # 12. Construct the final labels
        # ====================================================
        labels_flat = labels.ravel()
        labels_flat[selected_true_flat] = 0
        labels_flat[selected_fake_flat] = 1
        selected_fake_mask_flat = selected_fake_mask.ravel()
        selected_fake_mask_flat[selected_fake_flat] = True
        true_zero_count = int(np.sum(labels == 0))
        false_zero_count = int(np.sum(labels == 1))
        unlabeled_count = int(np.sum(labels == -1))
        print(
            f"Final training label statistics: "
            f"true zeros={true_zero_count}, "
            f"false zeros={false_zero_count}, "
            f"unlabeled={unlabeled_count}"
        )
        # ====================================================
        # 13. Construct forced labels for the final prediction
        # ====================================================
        force_true_zero_q_mask = (
            rule_true_zero_mask
            & (Q_np == 0)
        )
        selected_fake_zero_q_mask = (
            selected_fake_mask
            & (Q_np == 0)
        )
        force_fake_zero_q_mask = (
            known_fake_zero_q_mask
            | selected_fake_zero_q_mask
        )
        def apply_force_override_to_pred_labels(
            prediction_labels,
            stage_name=""
        ):
            true_wrong_as_fake = np.sum(
                force_true_zero_q_mask
                & (prediction_labels == 1)
            )
            fake_wrong_as_true = np.sum(
                force_fake_zero_q_mask
                & (prediction_labels == 0)
            )
            prediction_labels[force_true_zero_q_mask] = 0
            prediction_labels[force_fake_zero_q_mask] = 1
            return prediction_labels
        # ====================================================
        # 14. Construct discriminator training inputs
        # ====================================================
        print("Preparing discriminator training data...")
        X_discriminator_train_np = X_np.astype(
            np.float32,
            copy=True
        )
        X_discriminator_train_flat = (
            X_discriminator_train_np.ravel()
        )
        X_discriminator_train_flat[selected_fake_flat] = 0.0
        labels_float_np = labels.astype(np.float32)
        print("Discriminator training inputs constructed")
        # ====================================================
        # 15. Split the training and validation sets
        # ====================================================
        train_pixel_indices, val_pixel_indices = train_test_split(
            tissue_indices,
            test_size=0.2,
            random_state=42,
            shuffle=True
        )
        train_label_count = np.sum(
            labels[train_pixel_indices] != -1
        )
        val_label_count = np.sum(
            labels[val_pixel_indices] != -1
        )
        print(
            f"Number of tissue pixels used for the training/validation split: "
            f"{len(tissue_indices)}"
        )
        print(
            f"Number of tissue pixels in the training set: "
            f"{len(train_pixel_indices)}"
        )
        print(
            f"Number of tissue pixels in the validation set: "
            f"{len(val_pixel_indices)}"
        )
        print(
            f"Number of labels contributing to the training loss: "
            f"{train_label_count}"
        )
        print(
            f"Number of labels used for validation: "
            f"{val_label_count}"
        )
        if train_label_count == 0:
            raise RuntimeError(
                "The training set contains no positions with labels != -1; "
                "unable to train the discriminator."
            )
        if val_label_count == 0:
            print(
                "Warning: the validation set contains no positions with "
                "labels != -1; validation AUC cannot be computed normally."
            )
        # ====================================================
        # discriminator
        # ====================================================
        class PixelDiscriminator(nn.Module):
            def __init__(
                self,
                spectrum_dim,
                hidden_dim=512
            ):
                super().__init__()
                self.net = nn.Sequential(
                    nn.Linear(
                        spectrum_dim,
                        hidden_dim
                    ),
                    nn.LayerNorm(hidden_dim),
                    nn.ReLU(),
                    nn.Dropout(0.3),
                    nn.Linear(
                        hidden_dim,
                        hidden_dim // 2
                    ),
                    nn.LayerNorm(hidden_dim // 2),
                    nn.ReLU(),
                    nn.Dropout(0.3),
                    nn.Linear(
                        hidden_dim // 2,
                        spectrum_dim
                    ),
                    nn.Sigmoid()
                )
            def forward(self, spectrum):
                return self.net(spectrum)
        class PixelBatchDataset(torch.utils.data.Dataset):
            def __init__(
                self,
                pixel_indices,
                X_input,
                label_matrix
            ):
                self.pixel_indices = np.asarray(pixel_indices)
                self.X_input = X_input
                self.label_matrix = label_matrix
            def __len__(self):
                return len(self.pixel_indices)
            def __getitem__(self, idx):
                pixel_idx = self.pixel_indices[idx]
                spectrum = self.X_input[
                    pixel_idx,
                    :
                ]
                label_vec = self.label_matrix[
                    pixel_idx,
                    :
                ]
                return {
                    "spectrum": torch.from_numpy(spectrum).float(),
                    "label_vec": torch.from_numpy(label_vec).float(),
                    "pixel_idx": torch.tensor(
                        pixel_idx,
                        dtype=torch.long
                    )
                }
        set_torch_random_seed(
            stage1_torch_seed
        )
        batch_size = 2048
        train_dataset = PixelBatchDataset(
            train_pixel_indices,
            X_discriminator_train_np,
            labels_float_np
        )
        val_dataset = PixelBatchDataset(
            val_pixel_indices,
            X_discriminator_train_np,
            labels_float_np
        )
        train_loader = torch.utils.data.DataLoader(
            train_dataset,
            batch_size=batch_size,
            shuffle=True,
            num_workers=0
        )
        val_loader = torch.utils.data.DataLoader(
            val_dataset,
            batch_size=batch_size,
            shuffle=False,
            num_workers=0
        )
        discriminator = PixelDiscriminator(
            spectrum_dim=Dim,
            hidden_dim=512
        ).to(device)
        optimizer_D = torch.optim.AdamW(
            discriminator.parameters(),
            lr=1e-3,
            weight_decay=1e-4
        )
        best_val_auc = -1.0
        no_improve_count = 0
        patience_d = 8
        total_epochs_d = 100
        print("\nStarting discriminator training...")
        # ====================================================
        # 16. Train the discriminator
        # ====================================================
        for epoch in range(total_epochs_d):
            discriminator.train()
            train_loss_sum = 0.0
            train_valid_count = 0
            for batch in tqdm(
                train_loader,
                desc=(
                    f"Epoch {epoch + 1}/"
                    f"{total_epochs_d} Training"
                ),
                leave=False
            ):
                spectrum = batch["spectrum"].to(device)
                label_vec = batch["label_vec"].to(device)
                train_mask = label_vec != -1
                if train_mask.sum() == 0:
                    continue
                optimizer_D.zero_grad()
                probs = discriminator(spectrum)
                loss = F.binary_cross_entropy(
                    probs[train_mask],
                    label_vec[train_mask]
                )
                loss.backward()
                optimizer_D.step()
                n_valid = train_mask.sum().item()
                train_loss_sum += loss.item() * n_valid
                train_valid_count += n_valid
            train_loss_avg = train_loss_sum / max(train_valid_count, 1)
            # =================================================
            # Validation
            # =================================================
            discriminator.eval()
            val_loss_sum = 0.0
            val_valid_count = 0
            all_val_preds = []
            all_val_labels = []
            with torch.no_grad():
                for batch in val_loader:
                    spectrum = batch["spectrum"].to(device)
                    label_vec = batch["label_vec"].to(device)
                    val_mask = label_vec != -1
                    if val_mask.sum() == 0:
                        continue
                    probs = discriminator(spectrum)
                    loss = F.binary_cross_entropy(
                        probs[val_mask],
                        label_vec[val_mask]
                    )
                    n_valid = val_mask.sum().item()
                    val_loss_sum += loss.item() * n_valid
                    val_valid_count += n_valid
                    all_val_preds.extend(
                        probs[val_mask].detach().cpu().numpy()
                    )
                    all_val_labels.extend(
                        label_vec[val_mask].detach().cpu().numpy()
                    )
            val_loss_avg = val_loss_sum / max(val_valid_count, 1)
            if (
                len(all_val_labels) > 0
                and len(np.unique(all_val_labels)) > 1
            ):
                val_auc = roc_auc_score(
                    all_val_labels,
                    all_val_preds
                )
            else:
                val_auc = 0.0
            print(
                f"[Discriminator] "
                f"Epoch {epoch + 1:3d} | "
                f"Train Loss: {train_loss_avg:.4f} | "
                f"Val Loss: {val_loss_avg:.4f} | "
                f"Val AUC: {val_auc:.4f}"
            )
            if val_auc > best_val_auc:
                best_val_auc = val_auc
                no_improve_count = 0
                torch.save(
                    discriminator.state_dict(),
                    best_discriminator_path
                )
                print(
                    f"  → Best validation AUC updated: "
                    f"{best_val_auc:.4f}; model saved"
                )
            else:
                no_improve_count += 1
                print(
                    f"  → No improvement: "
                    f"{no_improve_count}/{patience_d}"
                )
                if no_improve_count >= patience_d:
                    print(
                        f"Discriminator early stopping triggered; "
                        f"best validation AUC: {best_val_auc:.4f}"
                    )
                    break
        # ====================================================
        # 17. Load the best discriminator
        # ====================================================
        discriminator.load_state_dict(
            torch.load(
                best_discriminator_path,
                weights_only=True
            )
        )
        discriminator.eval()
        # ====================================================
        # Validation-set evaluation report
        # ====================================================
        print("\nGenerating the validation-set evaluation report...")
        all_val_preds = []
        all_val_labels = []
        with torch.no_grad():
            for batch in val_loader:
                spectrum = batch["spectrum"].to(device)
                label_vec = batch["label_vec"].to(device)
                val_mask = label_vec != -1
                if val_mask.sum() == 0:
                    continue
                probs = discriminator(spectrum)
                all_val_preds.extend(
                    probs[val_mask].detach().cpu().numpy()
                )
                all_val_labels.extend(
                    label_vec[val_mask].detach().cpu().numpy()
                )
        all_val_preds_np = np.asarray(
            all_val_preds,
            dtype=np.float32
        )
        all_val_labels_np = np.asarray(
            all_val_labels
        ).astype(np.int32)
        if len(all_val_labels_np) > 0:
            all_val_preds_class = (
                all_val_preds_np > 0.5
            ).astype(int)
            print("\nModel evaluation report:")
            print(
                classification_report(
                    all_val_labels_np,
                    all_val_preds_class,
                    zero_division=0
                )
            )
            if len(np.unique(all_val_labels_np)) > 1:
                print(
                    f"ROC AUC: "
                    f"{roc_auc_score(all_val_labels_np, all_val_preds_np):.4f}"
                )
            else:
                print(
                    "The validation set contains only one class; "
                    "ROC AUC cannot be computed."
                )
        else:
            print("The validation set contains no evaluable labels.")
        # ====================================================
        # Validation-set ROC curve
        # ====================================================
        print("Generating the discriminator validation ROC curve...")
        roc_save_dir = os.path.join(
            cluster_vis_dir,
            "roc_curve"
        )
        os.makedirs(
            roc_save_dir,
            exist_ok=True
        )
        if (
            len(all_val_labels_np) > 0
            and len(np.unique(all_val_labels_np)) > 1
        ):
            fpr, tpr, thresholds = roc_curve(
                all_val_labels_np,
                all_val_preds_np
            )
            roc_auc_value = auc(fpr, tpr)
            roc_data_path = os.path.join(
                roc_save_dir,
                "roc_data.npz"
            )
            np.savez(
                roc_data_path,
                fpr=fpr,
                tpr=tpr,
                thresholds=thresholds,
                y_true=all_val_labels_np,
                y_score=all_val_preds_np,
                auc=roc_auc_value
            )
            plt.figure(figsize=(7, 6))
            plt.plot(
                fpr,
                tpr,
                color="darkorange",
                lw=2,
                label=f"ROC curve (AUC = {roc_auc_value:.4f})"
            )
            plt.plot(
                [0, 1],
                [0, 1],
                color="navy",
                lw=2,
                linestyle="--",
                label="Random guess"
            )
            plt.xlim([0.0, 1.0])
            plt.ylim([0.0, 1.05])
            plt.xlabel(
                "False Positive Rate",
                fontsize=12
            )
            plt.ylabel(
                "True Positive Rate",
                fontsize=12
            )
            plt.title(
                "Discriminator Validation ROC Curve",
                fontsize=14,
                fontweight="bold"
            )
            plt.legend(loc="lower right")
            plt.grid(alpha=0.3)
            roc_fig_path = os.path.join(
                roc_save_dir,
                "roc_curve.png"
            )
            plt.savefig(
                roc_fig_path,
                dpi=300,
                bbox_inches="tight"
            )
            plt.close()
            print(
                f"Validation ROC curve saved to: {roc_fig_path}"
            )
            print(
                f"Validation ROC data saved to: {roc_data_path}"
            )
            print(
                f"Validation ROC AUC: {roc_auc_value:.4f}"
            )
        else:
            print(
                "The validation set contains only one class or no labels; "
                "unable to generate the ROC curve."
            )
        # ====================================================
        # 18. Construct the final prediction inputs
        # ====================================================
        print("Constructing discriminator prediction inputs...")
        X_discriminator_pred_np = X_np.astype(
            np.float32,
            copy=True
        )
        X_discriminator_pred_np[Q_np == 0] = 0.0
        class PixelPredDataset(torch.utils.data.Dataset):
            def __init__(
                self,
                pixel_indices,
                X_input
            ):
                self.pixel_indices = np.asarray(pixel_indices)
                self.X_input = X_input
            def __len__(self):
                return len(self.pixel_indices)
            def __getitem__(self, idx):
                pixel_idx = self.pixel_indices[idx]
                spectrum = self.X_input[
                    pixel_idx,
                    :
                ]
                return {
                    "spectrum": torch.from_numpy(spectrum).float(),
                    "pixel_idx": torch.tensor(
                        pixel_idx,
                        dtype=torch.long
                    )
                }
        pred_pixel_indices = np.where(
            np.any(
                Q_np == 0,
                axis=1
            )
        )[0]
        print(
            f"Number of pixels requiring discrimination: "
            f"{len(pred_pixel_indices)}"
        )
        pred_dataset = PixelPredDataset(
            pred_pixel_indices,
            X_discriminator_pred_np
        )
        pred_loader = torch.utils.data.DataLoader(
            pred_dataset,
            batch_size=batch_size,
            shuffle=False,
            num_workers=0
        )
        pred_labels = np.full(
            (No, Dim),
            -1,
            dtype=np.int8
        )
        discriminator.eval()
        with torch.no_grad():
            for batch in tqdm(
                pred_loader,
                desc="Batch prediction"
            ):
                spectrum = batch["spectrum"].to(device)
                pixel_idx_batch = (
                    batch["pixel_idx"].cpu().numpy()
                )
                probs = discriminator(spectrum)
                y_pred_class = (
                    probs > 0.5
                ).detach().cpu().numpy().astype(np.int8)
                q_sub_mask = (
                    Q_np[pixel_idx_batch, :] == 0
                )
                row_in_batch, col_idx = np.where(q_sub_mask)
                if len(row_in_batch) > 0:
                    global_pixel_idx = (
                        pixel_idx_batch[row_in_batch]
                    )
                    pred_labels[
                        global_pixel_idx,
                        col_idx
                    ] = y_pred_class[
                        row_in_batch,
                        col_idx
                    ]
        # ====================================================
        # 19. Override incorrectly predicted labels
        # ====================================================
        pred_labels = apply_force_override_to_pred_labels(
            pred_labels,
            stage_name="after discriminator prediction"
        )
        print("=" * 50)
        print("Stage 1 completed")
        print("=" * 50)
    # ========================================================
    # Stage 2: GAT imputation task
    # ========================================================
    print("\n" + "=" * 50)
    print("Stage 2: Starting ESU + GAT imputation task")
    print("=" * 50)
    class ESULoss(nn.Module):
        def __init__(self, eps=1e-10):
            super().__init__()
            self.eps = eps
        def forward(self, X, mean_pred, s, M):
            batch_size, num_nodes, dim = X.shape
            X_flat = X.view(-1, dim)
            mean_flat = mean_pred.view(-1, dim)
            s_flat = s.view(-1, dim)
            M_flat = M.view(-1, dim)
            decay_term = (
                torch.exp(-s_flat)
                * torch.abs(X_flat - mean_flat)
            )
            sparse_term = 2 * s_flat
            masked_decay = decay_term * M_flat
            masked_sparse = sparse_term * M_flat
            total_elem = M_flat.sum() + self.eps
            esu_loss = (
                torch.sum(masked_decay)
                + torch.sum(masked_sparse)
            ) / total_elem
            return esu_loss
    esu_loss_fn = ESULoss(eps=1e-10)
    lambda_recon1 = 1.0

    set_torch_random_seed(
        stage2_torch_seed
    )

    generator = Generator(
        node_feat_dim=Dim
    ).to(device).float()
    optimizer_G = torch.optim.AdamW(
        [
            {
                "params": generator.parameters(),
                "weight_decay": 1e-4
            }
        ],
        lr=1e-4
    )
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer_G,
        mode="min",
        factor=0.5,
        patience=8
    )
    grad_scaler = torch.amp.GradScaler("cuda")
    def sample_Z(n_nodes, n_feats):
        return torch.tensor(
            np.random.uniform(
                0.0,
                0.005,
                size=[1, n_nodes, n_feats]
            ),
            device=device,
            dtype=torch.float32
        )
    eval_loader = NeighborLoader(
        graph_data,
        num_neighbors=[10, 10, 10],
        batch_size=2048,
        shuffle=False,
        num_workers=0
    )
    def evaluate_global_mae(current_generator, loader):
        current_generator.eval()
        abs_sum = 0.0
        elem_count = 0
        with torch.no_grad():
            for batch in loader:
                batch = batch.to(device)
                current_bs = batch.batch_size
                Z = sample_Z(
                    batch.num_nodes,
                    Dim
                )
                New_X = (
                    batch.m * batch.x
                    + (1 - batch.q) * Z.squeeze(0)
                ).unsqueeze(0)
                with torch.amp.autocast("cuda"):
                    mu_esu, _ = current_generator(
                        New_X,
                        batch.edge_index
                    )
                mask = batch.s_mask[:current_bs] == 0
                if mask.sum() > 0:
                    err = torch.abs(
                        mu_esu.squeeze(0)[:current_bs][mask]
                        - batch.x[:current_bs][mask]
                    )
                    abs_sum += err.sum().item()
                    elem_count += err.numel()
        current_generator.train()
        return abs_sum / max(elem_count, 1)
    train_loader = NeighborLoader(
        graph_data,
        num_neighbors=[10, 10, 10],
        batch_size=2048,
        shuffle=True,
        num_workers=0
    )
    total_epochs = 10000
    best_mae = float("inf")
    no_improve_count = 0
    patience = 8
    grad_clip_norm = 1.0
    for epoch in range(total_epochs):
        generator.train()
        epoch_loss_sum = 0.0
        epoch_mae_sum = 0.0
        count = 0
        pbar = tqdm(
            train_loader,
            desc=f"Epoch {epoch + 1}/{total_epochs}"
        )
        for batch in pbar:
            batch = batch.to(device)
            optimizer_G.zero_grad()
            current_bs = batch.batch_size
            with torch.amp.autocast("cuda"):
                Z = sample_Z(
                    batch.num_nodes,
                    Dim
                )
                New_X = (
                    batch.m * batch.x
                    + (1 - batch.q) * Z.squeeze(0)
                ).unsqueeze(0)
                mu_esu, s_esu = generator(
                    New_X,
                    batch.edge_index
                )
            with torch.amp.autocast(
                "cuda",
                enabled=False
            ):
                loss = esu_loss_fn(
                    batch.x[:current_bs].unsqueeze(0).float(),
                    mu_esu[:, :current_bs].float(),
                    s_esu[:, :current_bs].float(),
                    batch.m[:current_bs].unsqueeze(0).float()
                )
            with torch.no_grad():
                mask = batch.s_mask[:current_bs] == 0
                if mask.sum() > 0:
                    mae_loss = nn.L1Loss()(
                        mu_esu.squeeze(0)[:current_bs][mask],
                        batch.x[:current_bs][mask]
                    )
                else:
                    mae_loss = torch.tensor(
                        0.0,
                        device=device
                    )
            total_loss = loss * lambda_recon1
            grad_scaler.scale(total_loss).backward()
            grad_scaler.unscale_(optimizer_G)
            torch.nn.utils.clip_grad_norm_(
                generator.parameters(),
                max_norm=grad_clip_norm
            )
            grad_scaler.step(optimizer_G)
            grad_scaler.update()
            epoch_loss_sum += loss.item()
            epoch_mae_sum += mae_loss.item()
            count += 1
            pbar.set_postfix(
                {
                    "Loss": f"{loss.item():.4f}",
                    "Batch MAE": f"{mae_loss.item():.6f}"
                }
            )
        avg_loss = (
            epoch_loss_sum / count
            if count > 0
            else 0
        )

        eval_mae = evaluate_global_mae(
            generator,
            eval_loader
        )

        scheduler.step(avg_loss)

        current_lr = optimizer_G.param_groups[0]["lr"]

        print(
            f"[Summary Epoch {epoch + 1}] "
            f"Eval MAE: {eval_mae:.6f} | "
        )

        if eval_mae <= best_mae - 1e-6:
            best_mae = eval_mae
            no_improve_count = 0

            torch.save(
                {
                    "epoch": epoch,
                    "generator": generator.state_dict(),
                    "optimizer_G": optimizer_G.state_dict(),
                    "scheduler": scheduler.state_dict(),
                    "best_mae": best_mae,
                    "numpy_seed": int(
                        random_seed
                    ),
                    "base_torch_seed": int(
                        torch_seed
                    ),
                    "stage1_torch_seed": int(
                        stage1_torch_seed
                    ),
                    "stage2_torch_seed": int(
                        stage2_torch_seed
                    ),
                    "run_id": run_id,
                },
                best_full_model_path
            )

            print(
                f"  → Best model saved "
                f"(Best MAE: {best_mae:.6f})"
            )

            print(
                f"  → Early stopping counter reset: "
                f"0/{patience}"
            )

        else:
            no_improve_count += 1

            print(
                f"  → No MAE improvement: "
                f"{no_improve_count}/{patience} | "
                f"Best MAE: {best_mae:.6f} | "
                f"Current MAE: {eval_mae:.6f}"
            )

            if no_improve_count >= patience:
                print(
                    f"Early stopping triggered "
                    f"(Patience={patience}). "
                    f"Best MAE: {best_mae:.6f}; "
                    f"training finished"
                )
                break
    # ========================================================
    # GAT block-wise inference
    # ========================================================
    print("\nLoading the best model for block-wise inference...")
    checkpoint = torch.load(
        best_full_model_path,
        weights_only=True
    )
    generator.load_state_dict(checkpoint["generator"])
    generator.eval()
    imputed_mmap = np.memmap(
        temp_imputed_path,
        dtype="float32",
        mode="w+",
        shape=(No, Dim)
    )
    s_mmap = np.memmap(
        temp_s_path,
        dtype="float32",
        mode="w+",
        shape=(No, Dim)
    )
    with torch.no_grad():
        for batch in tqdm(
            eval_loader,
            desc="Performing block-wise inference"
        ):
            batch = batch.to(device)
            current_bs = batch.batch_size
            global_indices = (
                batch.n_id[:current_bs].cpu().numpy()
            )
            Z = sample_Z(
                batch.num_nodes,
                Dim
            )
            New_X = (
                batch.m * batch.x
                + (1 - batch.q) * Z.squeeze(0)
            )
            with torch.amp.autocast("cuda"):
                mu_esu, s_esu = generator(
                    New_X.unsqueeze(0),
                    batch.edge_index,
                )
            imputed_mmap[global_indices] = (
                mu_esu.squeeze(0)[:current_bs].cpu().numpy()
            )
            s_mmap[global_indices] = (
                s_esu.squeeze(0)[:current_bs].cpu().numpy()
            )
    imputed_mmap.flush()
    s_mmap.flush()
    # ========================================================
    # Reassemble the data on the CPU
    # ========================================================
    del imputed_mmap
    del s_mmap
    mu_esu_np = np.memmap(
        temp_imputed_path,
        dtype="float32",
        mode="r",
        shape=(No, Dim)
    )
    s_esu_np = np.memmap(
        temp_s_path,
        dtype="float32",
        mode="r",
        shape=(No, Dim)
    )
    try:
        print("Loading data into CPU memory...")
        mu_esu_np = np.array(mu_esu_np)
        s_esu_np = np.array(s_esu_np)
        imputed_data_np = (
            M_np * X_np
            + (1 - Q_np) * mu_esu_np
        )
        s_np_final = s_esu_np * M_np
    except MemoryError:
        print("Insufficient CPU memory")
        return None
    try:
        os.remove(temp_imputed_path)
        os.remove(temp_s_path)
    except:
        pass
    final_mae = np.mean(
        np.abs(
            X_np[S_np == 0]
            - imputed_data_np[S_np == 0]
        )
    )
    print(
        f"\nEvaluation completed | "
        f"Masked-position MAE: {final_mae:.6f}"
    )
    # ========================================================
    # Stage 3: Correct the imputation results using Stage 1
    # prediction labels
    # ========================================================
    final_imputed = imputed_data_np.copy()
    true_zero_pred_mask = (
        (pred_labels == 0)
        & (Q_np == 0)
    )
    true_zero_pred_mask[force_fake_zero_q_mask] = False
    final_imputed[true_zero_pred_mask] = 0
    print("Saving final results...")
    pd.DataFrame(final_imputed).to_csv(
        final_output_path,
        index=False
    )
    print(f"Final results saved to: {final_output_path}")
    # ========================================================
    # Final evaluation
    # ========================================================
    print("\n" + "=" * 50)
    print("Final evaluation")
    print("=" * 50)
    s_mask = S_np == 0
    original_mae = np.mean(
        np.abs(
            X_np[s_mask]
            - imputed_data_np[s_mask]
        )
    )
    final_mae = np.mean(
        np.abs(
            X_np[s_mask]
            - final_imputed[s_mask]
        )
    )
    run_metadata.update(
        {
            "status": "mae_computed",
            "feature_dimension": int(Dim),
            "best_validation_mae": float(
                checkpoint["best_mae"]
            ),
            "original_imputation_mae": float(
                original_mae
            ),
            "final_corrected_mae": float(
                final_mae
            ),
            "best_model_path": os.path.abspath(
                best_full_model_path
            ),
            "final_output_path": os.path.abspath(
                final_output_path
            ),
        }
    )

    save_run_metadata(
        metadata_path,
        run_metadata
    )

    print(
        f"Original imputation MAE: "
        f"{original_mae:.6f}"
    )

    print(
        f"Final corrected MAE: "
        f"{final_mae:.6f}"
    )

    print(
        f"Base PyTorch seed: "
        f"{torch_seed}"
    )

    print(
        f"Stage 1 PyTorch seed: "
        f"{stage1_torch_seed}"
    )

    print(
        f"Stage 2 PyTorch seed: "
        f"{stage2_torch_seed}"
    )

    print(
        f"Run metadata saved to: "
        f"{metadata_path}"
    )

    print(
        f"To reproduce this run, use: "
        f"--torch_Seed {torch_seed}"
    )
    # ========================================================
    # Visualization of prediction results at unlabeled positions
    # ========================================================
    print("Generating visualization of predictions at unlabeled positions...")
    unlabeled_vis_dir = os.path.join(
        output_dir,
        "unlabeled_visualization"
    )
    os.makedirs(
        unlabeled_vis_dir,
        exist_ok=True
    )
    unlabeled_mask = labels == -1
    for feature_idx in tqdm(
        range(Dim),
        desc="Generating unlabeled-position prediction plots"
    ):
        bg_channel = BG_np[:, 0].reshape(H, W)
        pred_channel = pred_labels[
            :,
            feature_idx
        ].reshape(H, W)
        unlabeled_channel = unlabeled_mask[
            :,
            feature_idx
        ].reshape(H, W)
        rgba_img = np.zeros(
            (H, W, 4),
            dtype=np.float32
        )
        rgba_img[:, :, 3] = 1.0
        blue_mask = (
            unlabeled_channel
            & (pred_channel == 0)
            & (bg_channel == 1)
        )
        rgba_img[blue_mask] = [
            0.0,
            0.0,
            1.0,
            1.0
        ]
        green_mask = (
            unlabeled_channel
            & (pred_channel == 1)
            & (bg_channel == 1)
        )
        rgba_img[green_mask] = [
            0.0,
            1.0,
            0.0,
            1.0
        ]
        plt.figure(figsize=(8, 6))
        plt.imshow(rgba_img)
        plt.title(
            f"Unlabeled Prediction m/z {feature_idx}",
            fontsize=12,
            fontweight="bold"
        )
        plt.axis("off")
        plt.savefig(
            os.path.join(
                unlabeled_vis_dir,
                f"unlabeled_pred_mz_{feature_idx:03d}.png"
            ),
            dpi=300,
            bbox_inches="tight"
        )
        plt.close()
    print(
        f"Unlabeled-position prediction visualizations saved to: "
        f"{unlabeled_vis_dir}"
    )

    run_metadata["status"] = "completed"

    save_run_metadata(
        metadata_path,
        run_metadata
    )

    print("Task completed")
    return final_imputed
__all__ = [
    "build_grid_8_neighbor_graph",
    "map_to_spatial_grid",
    "build_tissue_neighbor_edges",
    "moran_i_binary",
    "compute_cluster_moran_metrics",
    "run_pipeline",
]