"""
Unified entry point of the project.

python run.py \
    --input_NPZ data/kidney/data_132_205.npz \
    --input_Shape 132 205 \
    --processed_Dir proprecessed_data/kidney \
    --output_Dir results/kidney/DropMSI \
    --output_File DropMSI.csv \
    --gpu_ID 2

python run.py \
    --input_NPZ data/brain10um/brain10um_162_207.npz \
    --input_Shape 162 207 \
    --processed_Dir proprecessed_data/brain10um \
    --output_Dir results/brain10um/DropMSI \
    --output_File DropMSI.csv \
    --gpu_ID 2

python run.py \
    --input_NPZ data/HCC/HCC_711_1658.npz \
    --input_Shape 711 1658 \
    --processed_Dir proprecessed_data/HCC \
    --output_Dir results/HCC/DropMSI \
    --output_File DropMSI.csv \
    --gpu_ID 2
"""

import argparse
from pathlib import Path

from main import run_pipeline
from preprocessing import preprocess_data


# ============================================================
# Project root directory
# ============================================================

PROJECT_ROOT = Path(
    __file__
).resolve().parent


# ============================================================
# Default parameters
# ============================================================

DEFAULT_INPUT_NPZ = (PROJECT_ROOT / "data"/ "kidney"/ "data_132_205.npz")

DEFAULT_INPUT_SHAPE = [132,205]

DEFAULT_PROCESSED_DIR = (PROJECT_ROOT/ "proprecessed_data"/ "kidney")

DEFAULT_OUTPUT_DIR = (PROJECT_ROOT/ "results"/ "kidney"/"DropMSI")

DEFAULT_OUTPUT_FILE = ("DropMSI.csv")

DEFAULT_GPU_ID = 2
DEFAULT_RANDOM_SEED = 42
DEFAULT_TORCH_SEED = 3339952821474911485

# Parameters used in preprocessing
DEFAULT_MASK_RATE = 0.1
DEFAULT_PERCENTILE = 99.9
DEFAULT_PREPROCESS_CLUSTERS = 2
DEFAULT_KMEANS_RANDOM_STATE = 0
DEFAULT_BACKGROUND_THRESHOLD = 1e-3


def build_parser():
    """Default values"""

    parser = argparse.ArgumentParser(
        description=(
            "MSI preprocessing, zero discrimination "
            "and ESU-GAT imputation pipeline"
        ),
        formatter_class=(
            argparse.ArgumentDefaultsHelpFormatter
        )
    )

    # ========================================================
    # Input data
    # ========================================================

    parser.add_argument(
        "--input_NPZ",
        default=str(DEFAULT_INPUT_NPZ),
        help=(
            "Path to the input sparse MSI matrix NPZ file."
        )
    )

    parser.add_argument(
        "--input_Shape",
        type=int,
        nargs=2,
        default=DEFAULT_INPUT_SHAPE,
        metavar=("HEIGHT", "WIDTH"),
        help=(
            "MSI spatial dimensions"
        )
    )

    # ========================================================
    # Intermediate data and final result directories
    # ========================================================

    parser.add_argument(
        "--processed_Dir",
        default=str(DEFAULT_PROCESSED_DIR),
        help=(
            "Directory for files generated by preprocessing.py."
        )
    )

    parser.add_argument(
        "--output_Dir",
        default=str(DEFAULT_OUTPUT_DIR),
        help=(
            "Output directory for models, results, and visualization files."
        )
    )

    parser.add_argument(
        "--output_File",
        default=DEFAULT_OUTPUT_FILE,
        help=(
            "Filename of the final corrected imputation result."
        )
    )

    # ========================================================
    # Device and random seed
    # ========================================================

    parser.add_argument(
        "--gpu_ID",
        type=int,
        default=DEFAULT_GPU_ID,
        help=(
            "GPU ID to use when CUDA is available."
        )
    )
    parser.add_argument(
        "--random_Seed",
        type=int,
        default=DEFAULT_RANDOM_SEED,
        help=(
            "NumPy random seed passed to preprocessing.py "
            "and main.py."
        )
    )
    parser.add_argument(
        "--torch_Seed",
        type=int,
        default=DEFAULT_TORCH_SEED,
        help=(
            "Base PyTorch random seed. If omitted, a random "
            "seed will be generated and saved for the current run."
        )
    )

    # ========================================================
    # preprocessing.py parameters
    # ========================================================

    parser.add_argument(
        "--mask_Rate",
        type=float,
        default=DEFAULT_MASK_RATE,
        help=(
            "Random masking rate."
        )
    )

    parser.add_argument(
        "--percentile",
        type=float,
        default=DEFAULT_PERCENTILE,
        help=(
            "Percentile clipping parameter after TIC normalization."
        )
    )

    parser.add_argument(
        "--preprocess_Clusters",
        type=int,
        default=DEFAULT_PREPROCESS_CLUSTERS,
        help=(
            "Number of KMeans clusters in the preprocessing stage."
        )
    )

    parser.add_argument(
        "--kmeans_Random_State",
        type=int,
        default=DEFAULT_KMEANS_RANDOM_STATE,
        help=(
            "KMeans random_state in the preprocessing stage."
        )
    )

    parser.add_argument(
        "--background_Threshold",
        type=float,
        default=DEFAULT_BACKGROUND_THRESHOLD,
        help=(
            "Threshold compensation parameter for background identification."
        )
    )

    return parser


def validate_arguments(args, parser):

    height, width = args.input_Shape

    if height <= 0 or width <= 0:
        parser.error(
            "HEIGHT and WIDTH in --input_Shape "
            "must be positive integers."
        )

    if args.gpu_ID < 0:
        parser.error(
            "--gpu_ID cannot be less than 0."
        )
    if (
        args.torch_Seed is not None
        and args.torch_Seed < 0
    ):
        parser.error(
            "--torch_Seed cannot be less than 0."
        )

    if not 0.0 <= args.mask_Rate <= 1.0:
        parser.error(
            "--mask_Rate must be within the range [0, 1]."
        )

    if not 0.0 <= args.percentile <= 100.0:
        parser.error(
            "--percentile must be within the range [0, 100]."
        )

    if args.preprocess_Clusters <= 0:
        parser.error(
            "--preprocess_Clusters must be a positive integer."
        )


def print_configuration(args):
    """
    Print the parameters currently in use.
    """

    print("=" * 60)
    print("Current project configuration")
    print("=" * 60)

    print(
        f"Input NPZ file: "
        f"{args.input_NPZ}"
    )

    print(
        f"Input spatial dimensions: "
        f"{args.input_Shape[0]} × "
        f"{args.input_Shape[1]}"
    )

    print(
        "Feature dimension Dim: "
        "Automatically read from normalization.npy"
    )

    print(
        f"Preprocessing output directory: "
        f"{args.processed_Dir}"
    )

    print(
        f"Final result output directory: "
        f"{args.output_Dir}"
    )

    print(
        f"Final result filename: "
        f"{args.output_File}"
    )

    print(
        f"GPU ID: "
        f"{args.gpu_ID}"
    )

    print(
        f"NumPy random seed: "
        f"{args.random_Seed}"
    )
    print(
        f"PyTorch random seed: "
        f"{args.torch_Seed if args.torch_Seed is not None else 'Auto-generated'}"
    )
    print(
        f"Random masking rate: "
        f"{args.mask_Rate}"
    )

    print(
        f"Percentile clipping parameter: "
        f"{args.percentile}"
    )

    print(
        f"Number of preprocessing KMeans clusters: "
        f"{args.preprocess_Clusters}"
    )

    print(
        f"KMeans random_state: "
        f"{args.kmeans_Random_State}"
    )

    print(
        f"Background compensation threshold: "
        f"{args.background_Threshold}"
    )

    print("=" * 60)


def main():
    """
    Unified project entry point.
    """

    parser = build_parser()
    args = parser.parse_args()

    validate_arguments(
        args,
        parser
    )

    print_configuration(
        args
    )

    # ========================================================
    # Preprocessing
    # ========================================================

    print("\n" + "=" * 60)
    print("Stage 1: Starting data preprocessing")
    print("=" * 60)

    preprocessing_result = preprocess_data(
        input_npz=args.input_NPZ,
        output_dir=args.processed_Dir,
        random_seed=args.random_Seed,
        mask_rate=args.mask_Rate,
        percentile=args.percentile,
        n_clusters=args.preprocess_Clusters,
        kmeans_random_state=(
            args.kmeans_Random_State
        ),
        background_threshold=(
            args.background_Threshold
        )
    )

    print("\nPreprocessing files generated successfully:")

    print(
        f"normalization.npy: "
        f"{preprocessing_result['normalization_path']}"
    )

    print(
        f"training_observation.npy: "
        f"{preprocessing_result['missing_path']}"
    )

    print(
        f"0.1_mask.npy: "
        f"{preprocessing_result['mask_path']}"
    )

    print(
        f"tissue_mask.npy: "
        f"{preprocessing_result['background_path']}"
    )

    print(
        f"imputation_keep_mask.npy: "
        f"{preprocessing_result['q_path']}"
    )

    # ========================================================
    # Training, imputation, and result correction
    # ========================================================

    print("\n" + "=" * 60)
    print("Stage 2: Starting model training and imputation")
    print("=" * 60)

    final_imputed = run_pipeline(
        data_dir=args.processed_Dir,
        input_shape=args.input_Shape,
        output_dir=args.output_Dir,
        gpu_id=args.gpu_ID,
        random_seed=args.random_Seed,
        torch_seed=args.torch_Seed,
        output_filename=args.output_File
    )

    # ========================================================
    # Completion
    # ========================================================

    print("\n" + "=" * 60)

    if final_imputed is None:
        print(
            "The pipeline finished, but no final result was returned."
        )
    else:
        print(
            "The complete pipeline finished successfully."
        )

        print(
            f"Final result matrix shape: "
            f"{final_imputed.shape}"
        )

        print(
            f"Final result directory: "
            f"{args.output_Dir}"
        )

        print(
            f"Final result file: "
            f"{args.output_File}"
        )

    print("=" * 60)


if __name__ == "__main__":
    main()